// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package store is a generated GoMock package.
package store

import (
	department "demo-service/models/department"
	employee "demo-service/models/employee"
	reflect "reflect"

	gofr "developer.zopsmart.com/go/gofr/pkg/gofr"
	gomock "github.com/golang/mock/gomock"
)

// MockEmployee is a mock of Employee interface.
type MockEmployee struct {
	ctrl     *gomock.Controller
	recorder *MockEmployeeMockRecorder
}

// MockEmployeeMockRecorder is the mock recorder for MockEmployee.
type MockEmployeeMockRecorder struct {
	mock *MockEmployee
}

// NewMockEmployee creates a new mock instance.
func NewMockEmployee(ctrl *gomock.Controller) *MockEmployee {
	mock := &MockEmployee{ctrl: ctrl}
	mock.recorder = &MockEmployeeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmployee) EXPECT() *MockEmployeeMockRecorder {
	return m.recorder
}

// CountByDepartment mocks base method.
func (m *MockEmployee) CountByDepartment(ctx *gofr.Context, deptCode string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByDepartment", ctx, deptCode)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByDepartment indicates an expected call of CountByDepartment.
func (mr *MockEmployeeMockRecorder) CountByDepartment(ctx, deptCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByDepartment", reflect.TypeOf((*MockEmployee)(nil).CountByDepartment), ctx, deptCode)
}

// Create mocks base method.
func (m *MockEmployee) Create(ctx *gofr.Context, emp *employee.NewEmployee) (*employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, emp)
	ret0, _ := ret[0].(*employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockEmployeeMockRecorder) Create(ctx, emp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockEmployee)(nil).Create), ctx, emp)
}

// Delete mocks base method.
func (m *MockEmployee) Delete(ctx *gofr.Context, id int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockEmployeeMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEmployee)(nil).Delete), ctx, id)
}

// ExistsByEmail mocks base method.
func (m *MockEmployee) ExistsByEmail(ctx *gofr.Context, email string, excludeID *int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByEmail", ctx, email, excludeID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByEmail indicates an expected call of ExistsByEmail.
func (mr *MockEmployeeMockRecorder) ExistsByEmail(ctx, email, excludeID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByEmail", reflect.TypeOf((*MockEmployee)(nil).ExistsByEmail), ctx, email, excludeID)
}

// Get mocks base method.
func (m *MockEmployee) Get(ctx *gofr.Context, filter employee.Filter) ([]*employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, filter)
	ret0, _ := ret[0].([]*employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockEmployeeMockRecorder) Get(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockEmployee)(nil).Get), ctx, filter)
}

// GetById mocks base method.
func (m *MockEmployee) GetById(ctx *gofr.Context, id int) (*employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetById", ctx, id)
	ret0, _ := ret[0].(*employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetById indicates an expected call of GetById.
func (mr *MockEmployeeMockRecorder) GetById(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetById", reflect.TypeOf((*MockEmployee)(nil).GetById), ctx, id)
}

// Update mocks base method.
func (m *MockEmployee) Update(ctx *gofr.Context, id int, emp *employee.NewEmployee) (*employee.Employee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, emp)
	ret0, _ := ret[0].(*employee.Employee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockEmployeeMockRecorder) Update(ctx, id, emp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockEmployee)(nil).Update), ctx, id, emp)
}

// MockDepartment is a mock of Department interface.
type MockDepartment struct {
	ctrl     *gomock.Controller
	recorder *MockDepartmentMockRecorder
}

// MockDepartmentMockRecorder is the mock recorder for MockDepartment.
type MockDepartmentMockRecorder struct {
	mock *MockDepartment
}

// NewMockDepartment creates a new mock instance.
func NewMockDepartment(ctrl *gomock.Controller) *MockDepartment {
	mock := &MockDepartment{ctrl: ctrl}
	mock.recorder = &MockDepartmentMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDepartment) EXPECT() *MockDepartmentMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDepartment) Create(ctx *gofr.Context, dep *department.Department) (*department.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dep)
	ret0, _ := ret[0].(*department.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockDepartmentMockRecorder) Create(ctx, dep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDepartment)(nil).Create), ctx, dep)
}

// Delete mocks base method.
func (m *MockDepartment) Delete(ctx *gofr.Context, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockDepartmentMockRecorder) Delete(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDepartment)(nil).Delete), ctx, code)
}

// ExistsByName mocks base method.
func (m *MockDepartment) ExistsByName(ctx *gofr.Context, name string, excludeCode *string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByName", ctx, name, excludeCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByName indicates an expected call of ExistsByName.
func (mr *MockDepartmentMockRecorder) ExistsByName(ctx, name, excludeCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByName", reflect.TypeOf((*MockDepartment)(nil).ExistsByName), ctx, name, excludeCode)
}

// Get mocks base method.
func (m *MockDepartment) Get(ctx *gofr.Context) ([]*department.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].([]*department.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockDepartmentMockRecorder) Get(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockDepartment)(nil).Get), ctx)
}

// GetByCode mocks base method.
func (m *MockDepartment) GetByCode(ctx *gofr.Context, code string) (*department.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCode", ctx, code)
	ret0, _ := ret[0].(*department.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCode indicates an expected call of GetByCode.
func (mr *MockDepartmentMockRecorder) GetByCode(ctx, code interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCode", reflect.TypeOf((*MockDepartment)(nil).GetByCode), ctx, code)
}

// Update mocks base method.
func (m *MockDepartment) Update(ctx *gofr.Context, code string, dep *department.NewDepartment) (*department.Department, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, code, dep)
	ret0, _ := ret[0].(*department.Department)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockDepartmentMockRecorder) Update(ctx, code, dep interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDepartment)(nil).Update), ctx, code, dep)
}
